### ISSUE TITLE
Add a chapter about the environment for 'appimaged' applications

### ISSUE THREAD

**Issue by HiranChaudhuri** [AppImage/docs.appimage.org#70]
How stringent is the sandbox?
What filesystem can they access? How can access be given to data or configuration directories?
What network to they have access to? Is the hostname/ip/routing any different from native applications?
How can an application from inside an appimage run another application installed on the system (appimaged or native)?

**Comment by TheAssassin** [comment]
That "sandbox" stuff is pretty pointless. You can find the details on firejail's homepage. It doesn't impose a lot of limits (since it's using a generic profile that applies to all AppImages, it can't limit too much by default), but those even may break some apps. I wouldn't recommend using that.

Also, appimaged is pretty much dead, and has been deprecated years ago. The code has not been maintained and is likely full of bugs (it has been in the past). Some of its workflows create unnecessary vulnerabilities, too.

**Comment by HiranChaudhuri** [comment]
Thank you for the update. However that not really satisfies my request.

When an application is packaged into AppImage, it's entry point is AppRun.
What is the current directory when AppRun is invoked? What are other environment variables?

So far I have seen that the current working directory is flexible - depending from where a user invokes the AppImage. I have not seen any further environment variables. How is AppRun supposed to find it's subsequent files? Can the application inside the AppImage run executables that are outside the image? Say, a shell script runnind a command like "find". Would that find binary have to reside inside the AppImage? What is the case for other libraries?

These questions are not related to firejail or appimaged, although I will take a look.

Please do not put the response to the questions in this ticket. Instead put a chapter into the documentation, which can then be further refined.
