### ISSUE TITLE
"Other resources"?

### ISSUE THREAD

**Issue by probonopd** [AppImage/docs.appimage.org#8]
Why was my carefully crafted content moved to "Other resources"?
I disagree with this. Please keep URLs constant, don't move my stuff to "Other resources".
I need to be able to link to stuff under URLs that don't change, and I don't want "other-resources" to be part of the URL.

Thanks!

**Comment by probonopd** [comment]
Also please don't push `linuxdeploy` front and center while hiding `linuxdeployqt` at this point.

**Comment by TheAssassin** [comment]
@probonopd your content is simply not in a "guide" form, but basically "stuff that might be useful" at this point (actual user feedback). There's no real structure in it at the moment, and that's why it's been moved by me. I plan to rewrite your content partially to bring it into a more "guide-ish" form, but my time is limited as well. I've got a structure in mind already, but I will have to move content, reorder it so that it makes more sense for users. I'm trying to think like "what would I be interested in most when trying to make an AppImage for the first time". The "native binaries" packaging guide for instance is going to be moved into a separate subdirectory which will contain guides for different languages in the future, and things like support for updates, signing etc. are going to be put into some kind of "optional steps" directory. "What goes into an AppImage" will be integrated into the introduction, etc.

You said yourself that once linuxdeploy is ready, linuxdeployqt could be dropped. It's been ready for several weeks, and is already used by users. linuxdeployqt is not maintained actively any more, and suffers from a lot of legacy issues. Not even bug fixing is viable in parallel to the development of linuxdeploy.
Also, for linuxdeploy, we have a complete "packaging guide" available, the feedback for this "carefully crafted guide" is very positive so far, users like this guide form a lot.

Accusing me of "hiding" linuxdeployqt is a bit unfair. I write content for the new tool for obvious reasons. linuxdeployqt hasn't been removed from any of the pages.

Keeping links "consistent" is not possible yet, as we are far from a "finished" state where we could care about stability of our URLs. Especially the packaging guide is not considered "stable" yet, as I'm actively writing content for it. This is similar to you not being a fan of us trying to provide a stable ABI for libappimage, etc.

In my opinion, it should suffice if you provide a link to https://docs.appimage.org at this point. Due to the hierarchical structure of the documents, content can be found easily from the index page.

**Comment by probonopd** [comment]
OK, no offense meant, we should review together when it is time to retire `linuxdeployqt`. But the permalink topic is indeed an issue for me. For example I need to frequently point people to why it is a good idea to compile on the oldest possible system.

**Comment by TheAssassin** [comment]
I understand that, of course. As said before, the packaging guide is still WIP, the rest is fairly stable. I am writing a "style guide" at the moment, and I will add a chapter how to add redirects on changes.

The "concepts" etc. can be considered stable.

> And people don't typically want to read more than a paragraph or so.

Highly depends on the style of writing. When a guide is written well, and can be understood easily, people are willing to read more in my experience.
